version: '1.0.0'

services:
  latex-server:
    container_name: latex-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    # ✅ Build and then start, with error handling
    command: sh -c "npm run build || { echo '❌ Build failed'; exit 1; } && npm run start || { echo '❌ App failed to start'; exit 1; }"
    restart: unless-stopped
