version: "3.9"

services:
  latex-server:
    container_name: latex-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
    restart: unless-stopped
