version: '1.0.0'

services:
  latex-server:
    container_name: latex-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'  # e.g., 3000:3000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    # ✅ Start using PM2 runtime with ecosystem config
    command: >
      sh -c "npm install --omit=dev || { echo '❌ npm install failed'; exit 1; } 
      && npx pm2-runtime ecosystem.config.cjs"
    restart: unless-stopped
